'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { generatePreviewTsx } = require('../preview-generator');

const MANIFEST = {
  componentName: 'Avatar',
  importPath: '@/app/components/avatar',
  variants: [
    { size: 'xs', shape: 'circle' },
    { size: 'sm', shape: 'circle' },
    { size: 'sm', shape: 'square' },
  ],
  nonVariantProps: { name: '"John Doe"' },
};

test('emits a valid React Next.js page', () => {
  const tsx = generatePreviewTsx(MANIFEST);
  assert.match(tsx, /import \{ Avatar \} from "@\/app\/components\/avatar"/);
  assert.match(tsx, /export default function Page/);
  assert.match(tsx, /<main/);
});

test('emits one wrapper per variant with data-adhd-variant', () => {
  const tsx = generatePreviewTsx(MANIFEST);
  assert.equal(tsx.match(/data-adhd-variant=/g).length, 3);
  assert.match(tsx, /data-adhd-variant="shape=circle;size=xs"/);
  assert.match(tsx, /data-adhd-variant="shape=circle;size=sm"/);
  assert.match(tsx, /data-adhd-variant="shape=square;size=sm"/);
});

test('renders each variant with its props', () => {
  const tsx = generatePreviewTsx(MANIFEST);
  assert.match(tsx, /<Avatar name=\{"John Doe"\} size=\{"xs"\} shape=\{"circle"\} \/>/);
  assert.match(tsx, /<Avatar name=\{"John Doe"\} size=\{"sm"\} shape=\{"square"\} \/>/);
});

test('omits props whose value is null (component default takes over)', () => {
  const M = {
    componentName: 'Button',
    importPath: '@/components/button',
    variants: [{ variant: 'primary' }],
    nonVariantProps: { onClick: '() => {}', children: null },
  };
  const tsx = generatePreviewTsx(M);
  // onClick is included; children is omitted
  assert.match(tsx, /onClick=\{\(\) => \{\}\}/);
  assert.doesNotMatch(tsx, /children=/);
});

test('header comment marks the file as auto-generated', () => {
  const tsx = generatePreviewTsx(MANIFEST);
  assert.match(tsx, /Auto-generated by \/adhd:push-component/);
  assert.match(tsx, /Do not edit/);
});

test('skips undefined variant values (renders without that prop)', () => {
  const M = {
    componentName: 'Avatar',
    importPath: '@/components/avatar',
    variants: [{ size: 'xs', status: 'undefined' }, { size: 'xs', status: 'online' }],
    nonVariantProps: { name: '"John Doe"' },
  };
  const tsx = generatePreviewTsx(M);
  // First variant: status omitted (undefined)
  assert.match(tsx, /<Avatar name=\{"John Doe"\} size=\{"xs"\} \/>/);
  // Second variant: status set
  assert.match(tsx, /<Avatar name=\{"John Doe"\} size=\{"xs"\} status=\{"online"\} \/>/);
});

test('captureScript: true (default) injects the Figma capture script tag inside <main>', () => {
  const tsx = generatePreviewTsx(MANIFEST);
  assert.match(tsx, /<main[^>]*>\s*<script src="https:\/\/mcp\.figma\.com\/mcp\/html-to-design\/capture\.js"/);
});

test('captureScript: false omits the script tag (for testing)', () => {
  const tsx = generatePreviewTsx(MANIFEST, { captureScript: false });
  assert.doesNotMatch(tsx, /capture\.js/);
});
